name: Build CC-Job-Image-Base
run-name: Building CC-Job-Image-Base
on:
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: read
      packages: write
    env:
      platforms: linux/amd64,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker-Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.platforms }}

    #   - name: docker-auth
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GITHUB_TOKEN }}
    #       registry: ghcr.io

      -
        name: Build and Publish CC-Job-Image-Base
        uses: docker/build-push-action@v6
        with:
          push: false
          platforms: ${{ env.platforms }}
          tags: ghcr.io/test/cc-utils/job-image-base:latest
          file: Dockerfile.job-image-base
