name: Test Interpolation Failure

on:
  workflow_dispatch:
    inputs:
      post-process:
        type: choice
        default: none
        options:
          - component-cli
          - none

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ YAML Interpolation works
        run: echo "post-process = ${{ inputs.post-process }}"

      - name: ❌ Python compare with ${{ inputs.post-process }}
        shell: python
        run: |
          if '${{ inputs.post-process }}' == 'component-cli':
              print("✅ CONDITION MET")
          else:
              print("❌ CONDITION FAILED")

      - name: ✅ Python compare with env variable (works)
        shell: python
        env:
          POST_PROCESS: ${{ inputs.post-process }}
        run: |
          import os
          post_process = os.getenv("POST_PROCESS")
          print(f"POST_PROCESS={post_process}")
          if post_process == 'component-cli':
              print("✅ ENV CONDITION MET")
          else:
              print("❌ ENV CONDITION FAILED")
