name: test
on: push

jobs:
  test-auth:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/oci-auth
        with:
          oci-image-reference: europe-docker.pkg.dev/gardener-project
      - name: test
        shell: bash
        run: |
          git status

  run-build:
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        args:
          - name: test
            oci-repository: cc/test
            oci-platforms: linux/amd64
            tag: test
            dockerfile: Dockerfile.example
          - name: test2
            oci-repository: cc/test2
            oci-platforms: linux/amd64
            tag: test
            dockerfile: Dockerfile.example
    uses: ./.github/workflows/oci-ocm.yaml
    with:
      name: ${{ matrix.args.name }}
      oci-registry: 'ghcr.io/ccwienk/cc-utils'
      oci-repository: ${{ matrix.args.oci-repository }}
      oci-platforms: ${{ matrix.args.oci-platforms }}
      version: '1.2.3'
      dockerfile: ${{ matrix.args.dockerfile }}
